# Generated by Django 5.2.10 on 2026-01-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=200, unique=True)),
                ('model', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('production_year', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
