# Generated by Django 5.2.10 on 2026-01-14 19:26

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(default=reservations.models.create_reservation_code, max_length=200, unique=True),
        ),
    ]
